### PR TITLE
Remove extra reporting in RSpec3

### PR DESCRIPTION
**Pull request by evie404**
@clintkelly

Let's remove the reporting patch first to unblock us to RSpec 3. We can investigate how to add it back later.

### CODE REVIEW

**Comment by evie404** [comment]
this is meant for airbnb/rspec-gc-control :/

**Comment by MrJoy** [comment]
If you want to add a flag/option to make this configurable, I'd be happy to merge it.  I can deal with the style annoyances from Hound so don't worry about formatting conventions.

**Comment by evie404** [comment]
Thanks a lot!

We are in the process of upgrading our test suite to use RSpec 3 instead of RSpec 2. Originally, I was going to hack together some solution for this to work with RSpec 3 but had limited success. For now, I'm removing this gem in our test suite to unblock the upgrade, but I'd love to revisit and help add support for RSpec and add it back to our test suite.

**Comment by MrJoy** [comment]
/me nods

If I can find some time I'll try and revisit it myself but I may benefit from you nudging me when your schedule permits.

**Pull request closed without merging**
